// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARnLb1CSZSHcARDTM071vHg0t12rp3KfE',
    appId: '1:72695543122:web:4ec78bb1ece69bc16cb68b',
    messagingSenderId: '72695543122',
    projectId: 'primor-d8087',
    authDomain: 'primor-d8087.firebaseapp.com',
    storageBucket: 'primor-d8087.firebasestorage.app',
    measurementId: 'G-NNM49G0BLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWa46GdUjQ_2WcyNJ0RoCCiKMvHRvKvfY',
    appId: '1:72695543122:android:d27ec425eab75ad46cb68b',
    messagingSenderId: '72695543122',
    projectId: 'primor-d8087',
    storageBucket: 'primor-d8087.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4uaJtWHmoQpaV7eGqqQgUEPSMFXOwt_s',
    appId: '1:72695543122:ios:5cf930b7c2363f556cb68b',
    messagingSenderId: '72695543122',
    projectId: 'primor-d8087',
    storageBucket: 'primor-d8087.firebasestorage.app',
    iosBundleId: 'br.com.compromo.primorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4uaJtWHmoQpaV7eGqqQgUEPSMFXOwt_s',
    appId: '1:72695543122:ios:5cf930b7c2363f556cb68b',
    messagingSenderId: '72695543122',
    projectId: 'primor-d8087',
    storageBucket: 'primor-d8087.firebasestorage.app',
    iosBundleId: 'br.com.compromo.primorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARnLb1CSZSHcARDTM071vHg0t12rp3KfE',
    appId: '1:72695543122:web:a4a7e54f829f818b6cb68b',
    messagingSenderId: '72695543122',
    projectId: 'primor-d8087',
    authDomain: 'primor-d8087.firebaseapp.com',
    storageBucket: 'primor-d8087.firebasestorage.app',
    measurementId: 'G-KJPEHR2DMC',
  );
}
